[
  { flag: "🇶🇦", group: "A", position: 1, slug: "qatar", name: "Catar" },
  { flag: "🇪🇨", group: "A", position: 2, slug: "ecuador", name: "Ecuador" },
  { flag: "🇸🇳", group: "A", position: 3, slug: "senegal", name: "Senegal" },
  { flag: "🇳🇱", group: "A", position: 4, slug: "netherlands", name: "Países Bajos" },
  { flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "B", position: 1, slug: "england", name: "Inglaterra" },
  { flag: "🇮🇷", group: "B", position: 2, slug: "iran", name: "Irán" },
  { flag: "🇺🇸", group: "B", position: 3, slug: "usa", name: "Estados Unidos" },
  { flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", group: "B", position: 4, slug: "wales", name: "Gales" },
  { flag: "🇦🇷", group: "C", position: 1, slug: "argentina", name: "Argentina" },
  { flag: "🇸🇦", group: "C", position: 2, slug: "saudi_arabia", name: "Arabia Saudita" },
  { flag: "🇲🇽", group: "C", position: 3, slug: "mexico", name: "México" },
  { flag: "🇵🇱", group: "C", position: 4, slug: "poland", name: "Polonia" },
  { flag: "🇫🇷", group: "D", position: 1, slug: "france", name: "Francia" },
  { flag: "🇩🇰", group: "D", position: 2, slug: "denmark", name: "Dinamarca" },
  { flag: "🇹🇳", group: "D", position: 3, slug: "tunisia", name: "Túnez" },
  { flag: "🇦🇺", group: "D", position: 4, slug: "australia", name: "Australia" },
  { flag: "🇪🇸", group: "E", position: 1, slug: "spain", name: "España" },
  { flag: "🇩🇪", group: "E", position: 2, slug: "germany", name: "Alemania" },
  { flag: "🇯🇵", group: "E", position: 3, slug: "japan", name: "Japón" },
  { flag: "🇨🇷", group: "E", position: 4, slug: "costa_rica", name: "Costa Rica" },
  { flag: "🇧🇪", group: "F", position: 1, slug: "belgium", name: "Bélgica" },
  { flag: "🇨🇦", group: "F", position: 2, slug: "canada", name: "Canadá" },
  { flag: "🇲🇦", group: "F", position: 3, slug: "morocco", name: "Marruecos" },
  { flag: "🇭🇷", group: "F", position: 4, slug: "croatia", name: "Croacia" },
  { flag: "🇧🇷", group: "G", position: 1, slug: "brazil", name: "Brasil" },
  { flag: "🇷🇸", group: "G", position: 2, slug: "serbia", name: "Serbia" },
  { flag: "🇨🇭", group: "G", position: 3, slug: "switzerland", name: "Suiza" },
  { flag: "🇨🇲", group: "G", position: 4, slug: "cameroon", name: "Camerún" },
  { flag: "🇵🇹", group: "H", position: 1, slug: "portugal", name: "Portugal" },
  { flag: "🇬🇭", group: "H", position: 2, slug: "ghana", name: "Ghana" },
  { flag: "🇺🇾", group: "H", position: 3, slug: "uruguay", name: "Uruguay" },
  { flag: "🇰🇷", group: "H", position: 4, slug: "korea", name: "Corea del Sur" }
].each { |team| Team.create(team) }
